routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Admin routes
Route::name('admin.')->prefix('admin')->namespace('Admin')->group(function () {
    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Login
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login');

        // Forget and reset Password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('forgot_password');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset/{token}/{email?}', 'ResetPasswordController@showResetForm')->name('reset_password_link');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('reset_password');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        // Dashboard
        Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

        //cards
        Route::resource('cards','CardController');
        Route::resource('home','HomeContentController');
        // Profile
        Route::get('/profile', 'AdminController@profile')->name('profile');
        Route::post('/profile', 'AdminController@profileUpdate');
        Route::post('/password', 'AdminController@passwordUpdate')->name('password_update');

        // Logout
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

app/Models/Card.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Card extends Model
{
    protected $table = 'cards';

    protected $fillable = [
        'image',
        'title',
        'text_person'
    ];
}

app/Http/Controllers/Admin/CardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Card;
use Illuminate\Http\Request;
use App\Http\Requests\CardValidation as CardValidation;
class CardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cards = Card::paginate(10);

        return view('admin.cards.index',compact('cards'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cards.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CardValidation $request)
    {
        $data = $request->all();
        $path = $request->file('image')->store('imagens', 'public');
        $data['image'] = $path;

        $card = Card::create($data);

        return redirect()->route('admin.cards.index')->with([
            'type' => 'success',
            'message' => 'Card adicionado'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $card = Card::findOrFail($id);

        return view('admin.cards.edit',compact('card'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CardValidation $request, $id)
    {
        $data = $request->all();
        $card = Card::findOrFail($id);
        if (\File::exists('storage/'.$card->image) && $request->file('image')){
            \File::delete('storage/'.$card->image);
            $path = $request->file('image')->store('imagens', 'public');
            $data['image'] = $path;
        }

        $card->update($data);

        return redirect()->route('admin.cards.index')->with([
            'type' => 'success',
            'message' => 'Card atualizado com sucesso'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $card = Card::findOrFail($id);
        if (\File::exists('storage/'.$card->image)){
            \File::delete('storage/'.$card->image);
        }
        $card->delete();

        return redirect()->route('admin.cards.index')->with([
            'type' => 'success',
            'message' => 'Card deletado com sucesso'
        ]);
    }
}

resources/views/admin/cards/add.blade.php
@extends('admin.layouts.app', ['page' => 'cards'])

@section('title', 'Adicionar novo card')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Adicionar novo personagem
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('admin.cards.store') }}">
        @csrf
        <div class="form-group">
            <label for="title">Titulo do personagem</label>
            <input type="text" class="form-control"
                   name="title"
                   id="title"
                   required
            >
        </div>
        <div class="form-group">
            <label for="text_person">Texto do personagem</label>
            <textarea class="form-control"
                name="text_person"
                id="text_person"
                required
                placeholder="Texto do personagem"
            >{{ old('text_person') }}</textarea>
        </div>

        <div class="form-group">
            <label for="image">Imagem do personagem</label>
            <input type="file" class="form-control"
                   name="image"
                   required
            >
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Cadastrar
            </button>
        </div>
    </form>
</div>
@endsection

resources/views/admin/cards/edit.blade.php
@extends('admin.layouts.app', ['page' => 'cards'])

@section('title', 'Editar card')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Adicionar novo personagem
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('admin.cards.update',$card->id) }}">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="title">Titulo do personagem</label>
            <input type="text" class="form-control"
                   name="title"
                   id="title"
                   required
                   value="{{old('title',$card->title)}}"
            >
        </div>
        <div class="form-group">
            <label for="text_person">Texto do personagem</label>
            <textarea class="form-control"
                name="text_person"
                id="text_person"
                required
                placeholder="Texto do personagem"
            >{{ old('text_person',$card->text_person) }}</textarea>
        </div>
        <div class="form-group">
            <div class="row">
                <img style="width: 150px; height: auto" src="{{url('/storage/'.$card->image)}}" alt="">
            </div>
            <label for="image">Imagem do personagem</label>
            <input type="file" class="form-control"
                   name="image"
                   id="image"
            >
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Atualizar
            </button>
        </div>
    </form>
</div>
@endsection

resources/views/admin/cards/index.blade.php
@extends('admin.layouts.app', ['page' => 'cards'])

@section('title', 'Cards')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Configs
        </div>

        <div class="col-6 text-right">
            <a class="btn btn-md btn-square btn-secondary"
                href="{{ route('admin.cards.create') }}"
            >
                Adicionar novo personagem
            </a>
        </div>
    </div>
</div>

<div class="card-body m-2">
    <table class="table table-responsive-sm">
        <thead>
            <tr>
                <th>#
                <th>Titulo</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($cards as $card)
                <tr>
                    <td>{{ $card->id }}</td>
                    <td>{{ $card->title }}</td>
                    <td>
                        <a class="btn btn-pill btn-sm btn-warning"
                            href="{{ route('admin.cards.edit', ['config' => $card->id]) }}"
                        >
                            <i class="fa fa-pencil-square-o"></i>
                        </a>

                        <form action="{{ route('admin.cards.destroy', ['config' => $card->id]) }}"
                            method="POST"
                            class="inline pointer"
                        >
                            @csrf
                            @method('DELETE')

                            <a class="btn btn-pill btn-sm btn-danger"
                                onclick="if (confirm('Você tem certeza que deseja excluir?')) { this.parentNode.submit() }"
                            >
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{ $cards->links() }}
</div>
@endsection