routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Admin routes
Route::name('admin.')->prefix('admin')->namespace('Admin')->group(function () {
    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Login
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login');

        // Forget and reset Password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('forgot_password');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset/{token}/{email?}', 'ResetPasswordController@showResetForm')->name('reset_password_link');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('reset_password');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        // Dashboard
        Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

        //cards
        Route::resource('cards','CardController');
        Route::resource('home','HomeContentController');
        // Profile
        Route::get('/profile', 'AdminController@profile')->name('profile');
        Route::post('/profile', 'AdminController@profileUpdate');
        Route::post('/password', 'AdminController@passwordUpdate')->name('password_update');

        // Logout
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app', ['page' => 'dashboard'])

@section('title', 'Dashboard')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Dashboard
        </div>
    </div>
</div>

<div class="card-body m-2">
    <p>
        Admin Dashboard
    </p>
</div>
@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.app', ['page' => ''])

@section('title', 'Profile')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Atualizar perfil
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form method="post">
        @csrf

        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text"
                name="name"
                class="form-control"
                id="name"
                placeholder="Name"
                value="{{ old('name', $admin->name) }}"
            >
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input type="email"
                name="email"
                class="form-control"
                id="email"
                placeholder="Email address"
                value="{{ old('email', $admin->email) }}"
            >
        </div>

        <div class="form-group">
            <label for="username">Username</label>
            <input type="text"
                name="username"
                class="form-control"
                id="username"
                placeholder="Username"
                value="{{ old('username', $admin->username) }}"
            >
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
               Atualizar perfil
            </button>
        </div>
    </form>
</div>

{{-- Password update --}}
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
           Alterar senha
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form method="post" action="{{ route('admin.password_update') }}">
        @csrf

        <div class="form-group">
            <label for="current-password">Senha atual</label>
            <input type="password"
                name="current_password"
                class="form-control"
                id="current-password"
                placeholder="Senha atual"
                pattern=".{6,}"
                title="6 caracteres min"
            >
        </div>

        <div class="form-group">
            <label for="password">Nova senha</label>
            <input type="password"
                name="password"
                class="form-control"
                id="password"
                placeholder="Nova senha"
                pattern=".{6,}"
                title="6 caracteres min"
            >
        </div>

        <div class="form-group">
            <label for="confirm-password">Confirme nova senha</label>
            <input type="password"
                name="password_confirmation"
                class="form-control"
                id="confirm-password"
                placeholder="Confirme nova senha"
                pattern=".{6,}"
                title="6 caracteres min"
            >
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Alterar senha
            </button>
        </div>
    </form>
</div>
@endsection