routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Admin routes
Route::name('admin.')->prefix('admin')->namespace('Admin')->group(function () {
    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Login
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login');

        // Forget and reset Password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('forgot_password');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset/{token}/{email?}', 'ResetPasswordController@showResetForm')->name('reset_password_link');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('reset_password');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        // Dashboard
        Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

        //cards
        Route::resource('cards','CardController');
        Route::resource('home','HomeContentController');
        // Profile
        Route::get('/profile', 'AdminController@profile')->name('profile');
        Route::post('/profile', 'AdminController@profileUpdate');
        Route::post('/password', 'AdminController@passwordUpdate')->name('password_update');

        // Logout
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

app/Models/HomeContent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HomeContent extends Model
{
    protected $table = 'home_contents';

    protected $fillable = [
        'image_background',
        'title_game',
        'phrase',
        'theme_spotlight',
        'form_desc'
    ];
}

app/Http/Controllers/Admin/HomeContentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\HomeContent;
use Illuminate\Http\Request;
use App\Http\Requests\HomeContentValidation as HomeContentValidation;

class HomeContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $home_contents = HomeContent::findOrFail($id);

        return view('admin.home_contents.edit',compact('home_contents'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(HomeContentValidation $request, $id)
    {
        $data = $request->all();
        $home_contents = HomeContent::findOrFail($id);
        if ($request->file('image_background')){
            \File::delete('storage/'.$home_contents->image);
            $path = $request->file('image_background')->store('imagens', 'public');
            $data['image_background'] = $path;
        }
        if ($request->file('theme_spotlight')){
            \File::delete('storage/'.$home_contents->image);
            $path = $request->file('theme_spotlight')->store('imagens', 'public');
            $data['theme_spotlight'] = $path;
        }

        $home_contents->update($data);

        return redirect()->back()->with([
            'type' => 'success',
            'message' => 'Conteúdo atualizado com sucesso'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/home_contents/edit.blade.php
@extends('admin.layouts.app', ['page' => 'cards'])

@section('title', 'Editar conteúdo inicial')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Adicionar novo personagem
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" enctype="multipart/form-data" action="{{ route('admin.home.update',$home_contents->id) }}">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="title_game">Titulo do jogo</label>
            <input type="text" class="form-control"
                   name="title_game"
                   id="title_game"
                   required
                   value="{{old('title',$home_contents->title_game)}}"
            >
        </div>
        <div class="form-group">
            <label for="phrase">Frase inicio</label>
            <textarea class="form-control"
                name="phrase"
                id="phrase"
                required
                placeholder="Frase inicial"
            >{{ old('text_person',$home_contents->phrase) }}</textarea>
        </div>
        <div class="form-group">
            <label for="form_desc">Descricao do formulário de contato</label>
            <textarea class="form-control"
                      name="form_desc"
                      id="form_desc"
                      required
                      placeholder="Descrição do formulário"
            >{{ old('text_person',$home_contents->form_desc) }}</textarea>
        </div>
       <div class="row">
           <div class="col-md-6">
               <div class="form-group">
                   <div class="row">
                       <img style="width: 150px; height: auto" src="{{url('/storage/'.$home_contents->image_background)}}" alt="">
                   </div>
                   <label for="image_background">Imagem do background </label>
                   <input type="file" class="form-control"
                          name="image_background"
                          id="image_background"
                   >
               </div>
           </div>
           <div class="col-md-6">
               <div class="form-group">
                   <div class="row">
                       <img style="width: 150px; height: auto" src="{{url('/storage/'.$home_contents->theme_spotlight)}}" alt="">
                   </div>
                   <label for="theme_spotlight">Imagem de destaque</label>
                   <input type="file" class="form-control"
                          name="theme_spotlight"
                          id="theme_spotlight"
                   >
               </div>
           </div>
       </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Atualizar
            </button>
        </div>
    </form>
</div>
@endsection